name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect project type
        id: project-type
        run: |
          if [ -f "requirements.txt" ] || [ -f "setup.py" ]; then
            echo "type=python" >> $GITHUB_OUTPUT
          elif [ -f "go.mod" ] || [ -f "main.go" ]; then
            echo "type=go" >> $GITHUB_OUTPUT
          else
            echo "type=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python
        if: steps.project-type.outputs.type == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        if: steps.project-type.outputs.type == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Go
        if: steps.project-type.outputs.type == 'go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Go binary
        if: steps.project-type.outputs.type == 'go'
        run: go build -v -o app ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.passwd }}  # 使用你在 GitHub Secrets 中创建的 'passwd' 密钥

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest  # <-- 手动修改为你的 GitHub 用户名和镜像名称
          platforms: linux/amd64,linux/arm64
